### ISSUE TITLE
inline::c 0.75 fails to write Makefile.PL

### ISSUE THREAD

**Issue by dankowitz** [ingydotnet/inline-c-pm#46]
I’m trying to install modules Inline::C and Pegex into a Perl 5 version 12 installation.
And the same error occurs:

syntax error at Makefile.PL line 13, near "install_share dist"
BEGIN not safe after errors--compilation aborted at Makefile.PL line 86.
Warning: No success on command[/usr/local/bin/perl Makefile.PL PREFIX=/usr/local/lib/perl5/5.12.4]
 INGY/Inline-C-0.75.tar.gz
 /usr/local/bin/perl Makefile.PL PREFIX=/usr/local/lib/perl5/5.12.4 -- NOT OK
Running make test
 Make had some problems, won't test
Running make install
 Make had some problems, won't install
Failed during this command:
INGY/Inline-C-0.75.tar.gz                    : writemakefile NO '/usr/local/bin/perl Makefile.PL PREFIX=/usr/local/lib/perl5/5.12.4' returned status 65280

Here’s what the Makefile.PL looks like at point of failure:

use File::ShareDir::Install;
$File::ShareDir::Install::INCLUDE_DOTFILES = 1;
$File::ShareDir::Install::INCLUDE_DOTDIRS = 1;
install_share dist => "share";   <<<<< line 13

The other pre-reqs are installed, along with File::ShareDir::Install  (version 0.10)

What can I do to solve or get around this???
Thanks for ANY suggestions!

**Comment by sisyphus** [comment]
Suggestions given on perlmonks yesterday included upgrading File::ShareDir::Install to the latest version and upgrading ExtUtils::MakeMaker to 7.04.
(See http://www.perlmonks.org/?node_id=1132041)
Neither of those suggestions helped ?

Cheers,
Rob

**Comment by dankowitz** [comment]
Hello Rob,
Thanks for your suggestions - things aren’t working yet though….
I did upgrade to latest File::ShareDir::Install 0.10 previously
and to ExtUtils::MakeMaker 7.04 now.
Just tried to download Inline::C 0.75 again for a clean install from search.cpan.org<http://search.cpan.org>, but the file is no longer available!

[root@sma Inline-C-0.75]# wget http://search.cpan.org/CPAN/authors/id/I/IN/INGY/Inline-C-0.75.tar.gz
--2015-06-26 19:02:00--  http://search.cpan.org/CPAN/authors/id/I/IN/INGY/Inline-C-0.75.tar.gz
Resolving search.cpan.org<http://search.cpan.org>... 199.15.177.162, 207.171.7.59
Connecting to search.cpan.org<http://search.cpan.org>|199.15.177.162|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.cpan.org/authors/id/I/IN/INGY/Inline-C-0.75.tar.gz [following]
--2015-06-26 19:02:01--  http://www.cpan.org/authors/id/I/IN/INGY/Inline-C-0.75.tar.gz
Resolving www.cpan.org<http://www.cpan.org>... 207.171.7.91, 2607:f238:3::91:1
Connecting to www.cpan.org<http://www.cpan.org>|207.171.7.91|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72949 (71K) [application/x-gzip]
Inline-C-0.75.tar.gz: No such file or directory

So tried to install from cpan - same result:

 CPAN.pm: Going to build I/IN/INGY/Inline-C-0.75.tar.gz

syntax error at Makefile.PL line 13, near "install_share dist"
BEGIN not safe after errors--compilation aborted at Makefile.PL line 86.
Warning: No success on command[/usr/local/bin/perl Makefile.PL PREFIX=/usr/local/lib/perl5/5.12.4]
  INGY/Inline-C-0.75.tar.gz
  /usr/local/bin/perl Makefile.PL PREFIX=/usr/local/lib/perl5/5.12.4 -- NOT OK
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install
Failed during this command:
 INGY/Inline-C-0.75.tar.gz                    : writemakefile NO '/usr/local/bin/perl Makefile.PL PREFIX=/usr/local/lib/perl5/5.12.4' returned status 65280


On Jun 26, 2015, at 6:41 PM, sisyphus <notifications@github.com<mailto:notifications@github.com>> wrote:


Suggestions given on perlmonks yesterday included upgrading File::ShareDir::Install to the latest version and upgrading ExtUtils::MakeMaker to 7.04.
(See http://www.perlmonks.org/?node_id=1132041)
Neither of those suggestions helped ?

Cheers,
Rob

**Comment by sisyphus** [comment]
It's going to be difficult for me to work out what has gone awry here - since I don't have a perl that replicates the behaviour.
Version 5.12.4 is rather old, and perhaps not very widely tested, and I'm wondering whether it's just that you've come upon an obscure bug with that version of perl.
Best thing would be for you to put the Makefile.PL in some directory (any directory) and keep trying various things (anything) to see if you can get it to do something other than spit out the same useless error message.
For example:
 Does running without strict make a difference ?
 Does it make a difference if you remove the braces ('{' and '}') surrounding the "package MY" stuff ?
 Does it make a difference if you begin the Makefile.PL with:
  BEGIN {use File::ShareDir::Install};
 ??
And anything else you can think of. (No need to be sensible in what you test ... there's not much sense in the above suggestions ;-)

I've just downloaded 5.12.4 source so I can build that version of perl, and perhaps replicate the problem. But if I can't reproduce the behaviour then I've got bugger-all chance of being able to  provide a solution.
So ... I'll get to and try to reproduce the problem, but in the meantime it would be good if you could poke and prod at the Makefile.PL and see if you can shed any light on what's going wrong.

Cheers,
Rob

**Comment by sisyphus** [comment]
No problems for me installing Inline-C-0.75 on perl-5.12.4 on Windows 8 && Ubuntu-14.04.
Which means I'm done ... at least until someone comes up with something to work on.

The OP might also like to give us the output of "perl -V" in case there's something telling in that.

Cheers,
Rob

**Comment by mohawk2** [comment]
Is this still failing or can it be closed?
