### ISSUE TITLE
Inline::C 0.77 t/01syntax.t test problem?

### ISSUE THREAD

**Issue by aero** [ingydotnet/inline-c-pm#64]
I have tried to install Inline::C 0.77 on linux machine.

t/01syntax.t test generates lots of subprocesses and doesn't completed.

As you can see, http://matrix.cpantesters.org/?dist=Inline-C+0.77 page does not show any received test results.

**Comment by perlpunk** [comment]
@aero  Currently the processing of reports is slow, that's why the matrix page isn't showing anything.
But you will find a link "Matrix via log.txt".
http://fast-matrix.cpantesters.org/?dist=Inline-C%200.77
There you can see that reports are coming in, but you can only see PASS or FAIL, not the report content.

So there are many PASS reports.
Could you add some details about your system? Do you get any output at all?
thanks

**Comment by aero** [comment]
@perlpunk 
I have 3 versions of installed perl.
1. 5.20-thread
2. 5.20
3. 5.24-thread

I tried to install Inline::C 0.77 on 2,3. they work well.
2,3 are clean installed perl.

but only 1 has problem.
It's forced-upgraded perl by overwriting 5.20.0 -> 5.20.1 -> 5.20.2 -> 5.20.3.

so I tested again with perl-5.20.3 clean install, It works well.

I think the problem comes from nonclean installed perl.
